# Generated by Django 4.2.3 on 2023-07-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_equipos_venta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipos',
            new_name='Equipo',
        ),
    ]
